var btn = '<div id="restart" onclick="restart()"><div class="btn red">Начать заново <i class="fas fa-redo-alt"></i><div class="btn__blobs"><div></div><div></div><div></div></div></div></div>';
	
function slowScroll (id) {
	var offset = 0;
	if ($(window).width () > 992)
		offset = 50;
    $('html, body').animate({
       	scrollTop: $(id).offset().top - offset
    }, 500);
}

function restart() {
	$("#linkedCourses").empty();
	$("#test").prev().text("Для чего вы хотите изучить программирование?");
	$("#test").html("<div onclick='chooseProffesionalSkills_games()'><div><img src='/img/lang_test/games.svg' alt='Создание игр'><p>Создание игр</p></div></div><div onclick='chooseProffesionalSkills_mobile()'><div><img src='/img/lang_test/mobile.svg' alt='Мобильные приложения'><p>Мобильные приложения</p></div></div><div onclick='chooseProffesionalSkills_web()'><div><img src='/img/lang_test/web.svg' alt='Веб разработка'><p>Веб разработка</p></div></div><div onclick='chooseProffesionalSkills_soft()'><div><img src='/img/lang_test/comp.svg' alt='Софт для компьютеров'><p>Софт для компьютеров</p></div></div><div onclick='chooseProffesionalSkills_data()'><div><img src='/img/lang_test/data.svg' alt='Обработка данных'><p>Обработка данных</p></div></div><div onclick='chooseProffesionalSkills_ai()'><div><img src='/img/lang_test/robot.svg' alt='Создание искусственного интеллекта'><p>Создание искусственного интеллекта</p></div></div>");
	slowScroll('.main-wrapper.container');
}

function chooseProffesionalSkills_games() {
	$("#test").prev().text("Под какие платформы вы хотите создавать игры?");
	$("#test").html("<div onclick='chooseProffesionalSkills_games_mobile()'><div><img src='/img/lang_test/mobile.svg' alt='Под мобильные телефоны'><p>Под мобильные телефоны</p></div></div><div onclick='chooseProffesionalSkills_games_pc()'><div><img src='/img/lang_test/pc_console.svg' alt='Компьютеры и игровые консоли'><p>Компьютеры и игровые консоли</p></div></div><div onclick='chooseProffesionalSkills_games_virtual()'><div><img src='/img/lang_test/virtual.svg' alt='Виртуальная реальность'><p>Виртуальная реальность</p></div></div><div onclick='chooseProffesionalSkills_games_web()'><div><img src='/img/lang_test/web_game.svg' alt='Web игра'><p>Web игра</p></div></div>");
}

function chooseProffesionalSkills_games_mobile() {
	$("#test").prev().text("Какой тип игры вы бы хотели разрабатывать?");
	$("#test").html("<div onclick='chooseProffesionalSkills_games_mobile_2d()'><div><img src='/img/lang_test/simple-game.svg' alt='2D игры'><p>2D игры</p></div></div><div onclick='chooseProffesionalSkills_games_mobile_3d()'><div><img src='/img/lang_test/games.svg' alt='3D игры'><p>3D игры</p></div></div>");
}

function chooseProffesionalSkills_games_mobile_2d() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/unity.svg' alt='C#'><h3>Движок Unity</h3><a href='/tag/unity' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Реализация мобильных игр намного удобнее при помощи игровых движков. Для создания 2D игр под мобильные устройства стоит использовать игровой движок Unity или Godot. Они позволяют создавать игры сразу под несколько платформ (iOS, Android) и обладают большим набором функционала.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/intensive/unity'><div class='course-img'><img src='https://itproger.com/img/intensivs/unity.svg' alt='Изучение Unity с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Unity разработчик</span></a></div><div class='course'><a href='https://itproger.com/course/unity'><div class='course-img'><img src='https://itproger.com/img/courses/1476982185.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Создание игр на Unity 5 | Начало</span></a></div><div class='course'><a href='http://itproger.com/course/godot'><div class='course-img'><img src='https://itproger.com/img/courses/1614851062.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Уроки Godot Engine</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_games_mobile_3d() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/unity.svg' alt='C#'><h3>Движок Unity</h3><a href='/tag/unity' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Реализация мобильных игр намного удобнее при помощи игровых движков. Для создания 3D игр под мобильные устройства стоит использовать игровой движок Unity. Он позволяет создавать игры сразу под несколько платформ (iOS, Android) и обладает большим набором функционала.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/intensive/unity'><div class='course-img'><img src='https://itproger.com/img/intensivs/unity.svg' alt='Изучение Unity с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Unity разработчик</span></a></div><div class='course'><a href='https://itproger.com/course/unity'><div class='course-img'><img src='https://itproger.com/img/courses/1476982185.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Создание игр на Unity 5 | Начало</span></a></div><div class='course'><a href='https://itproger.com/course/unity-gamedev'><div class='course-img'><img src='https://itproger.com/img/courses/1588400880.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Unity GameDev / Разработка игры на Unity</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_games_pc() {
	$("#test").prev().text("Какой тип игры вы бы хотели разрабатывать?");
	$("#test").html("<div onclick='chooseProffesionalSkills_games_pc_indie()'><div><img src='/img/lang_test/simple-game.svg' alt='Небольшие игры'><p>Небольшие игры</p></div></div><div onclick='chooseProffesionalSkills_games_pc_aaa()'><div><img src='/img/lang_test/games.svg' alt='Крупные проекты'><p>Крупные проекты</p></div></div>");
}

function chooseProffesionalSkills_games_pc_indie() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/csharp.svg' alt='C#'><h3>Язык C#</h3><a href='/tag/csharp' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Для создания небольших инди игр зачастую используется язык C# вместе с движком Unity. Всю графическую работу вы можете выполнить внутри движка, а для написания функционала использовать язык C#.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/csharp'><div class='course-img'><img src='https://itproger.com/img/courses/1477042680.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение языка C# для начинающих</span></a></div><div class='course'><a href='https://itproger.com/intensive/unity'><div class='course-img'><img src='https://itproger.com/img/intensivs/unity.svg' alt='Изучение Unity с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Unity разработчик</span></a></div><div class='course'><a href='https://itproger.com/course/unity-gamedev'><div class='course-img'><img src='https://itproger.com/img/courses/1588400880.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Unity GameDev / Разработка игры на Unity</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_games_pc_aaa() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/cpp.svg' alt='C++'><h3>Язык C++</h3><a href='/tag/cpp' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Для создания крупных игр со множеством элемнетов вам стоит изучать язык C++. Язык позволяет написать свой игровой движок или же воспользоваться уже готовыми движками, например, движком <b>Unreal Engine 4</b>. C++ позволяет создавать игры класса ААА, которые считаются наиболее передовыми играми современности.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/cpp'><div class='course-img'><img src='https://itproger.com/img/courses/1477043167.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение C++ с нуля</span></a></div><div class='course'><a href='https://itproger.com/intensive/cpp'><div class='course-img'><img src='https://itproger.com/img/intensivs/cpp.svg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия C++ разработчик</span></a></div><div class='course'><a href='https://itproger.com/course/cpp-snake'><div class='course-img'><img src='https://itproger.com/img/courses/1491734473.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Простая игра на C++</span></a></div><div class='course'><a href='https://itproger.com/course/unreal-engine'><div class='course-img'><img src='https://itproger.com/img/courses/1491837415.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Unreal Engine</span></a></div><div class='course'><a href='https://itproger.com/course/unreal-engine'><div class='course-img'><img src='https://itproger.com/img/courses/1520445191.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Создание игры на Unreal Engine 4 / FPS шутер</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_games_virtual() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/csharp.svg' alt='C#'><h3>Язык C#</h3><a href='/tag/csharp' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Для игр с виртуальной реальностью необходимо изучать язык C#. Используя C#, а также игровой движок Unity, вы сможете создавать полноценные приложения и игры с использованием технологии AR.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/csharp'><div class='course-img'><img src='https://itproger.com/img/courses/1477042680.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение языка C# для начинающих</span></a></div><div class='course'><a href='https://itproger.com/intensive/unity'><div class='course-img'><img src='https://itproger.com/img/intensivs/unity.svg' alt='Изучение Unity с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Unity разработчик</span></a></div><div class='course'><a href='https://itproger.com/course/unity-ar'><div class='course-img'><img src='https://itproger.com/img/courses/1551604154.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Дополненная реальность / Создание Unity AR приложений</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_games_web() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/javascript.svg' alt='Java'><h3>Язык JavaScript</h3><a href='/tag/javascript' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Для создания веб-игр можно использовать игровые движки такие, как: Unity, Unreal, GameMaker. Плюс можно писать игру с чистого листа на основе языка JavaScript. Для построения подобных игр вам необходимо изучить: HTML, CSS, JS и технологию Canvas. На ресурсе мы уже публиковали материалы по созданию игр на чистом JavaScript. Вы можете ознакомиться со статьей <a href='http://itproger.com/news/104'>здесь</a>.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/javascript'><div class='course-img'><img src='https://itproger.com/img/courses/1476977754.jpg' alt='Изучение JavaScript'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение JavaScript</span></a></div><div class='course'><a href='https://itproger.com/course/javascript-full'><div class='course-img'><img src='https://itproger.com/img/courses/1532598979.jpg' alt='Изучение JavaScript: от нуля и до создания сайта'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение JavaScript: от нуля и до создания сайта</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_mobile() {
	$("#test").prev().text("Под какую платформу вы хотите писать программы?");
	$("#test").html("<div onclick='chooseProffesionalSkills_mobile_ios()'><div><img src='/img/lang_test/apple.svg' alt='iOS'><p>iOS</p></div></div><div onclick='chooseProffesionalSkills_mobile_android()'><div><img src='/img/lang_test/android.svg' alt='Андроид'><p>Андроид</p></div></div>");
}

function chooseProffesionalSkills_mobile_ios() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/swift.svg' alt='swift'><h3>Язык Swift</h3><a href='/tag/ios' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Разработка приложений и игр для iOS и Macintosh производится на языке <b>Swift</b>. Язык продвигается компанией Apple, поэтому его популярность постоянно растет. Язык имеет простой синтаксис, удобную среду разработки и большую функциональность, что позволяет создавать проекты любой сложности.</p><h3>Подходящий курс</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/swift'><div class='course-img'><img src='https://itproger.com/img/courses/1523436361.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Уроки Swift для начинающих</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_mobile_android() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/java.svg' alt='Java'><h3>Язык Java</h3><a href='/tag/java' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Java - удобный, быстрый и многофункционалный язык, который подходит для множества сфер, начиная от веба и заканчивая созданием игр под мобильные устройства и ПК.<br><br>Язык Java прост в изучении, обладает гигантским количеством библиотек и обширным списком обучающих материалов. Реализация всех Андроид программ зачастую ведётся в Android Studio с использованием языка Java.<br><br>Также советуем обратить внимание на язык Kotlin, который является усовершенствованной версией языка Java.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/java'><div class='course-img'><img src='https://itproger.com/img/courses/1478531306.jpg' alt='Изучение Java с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Java с нуля</span></a></div><div class='course'><a href='https://itproger.com/intensive/java'><div class='course-img'><img src='https://itproger.com/img/intensivs/java.svg' alt='Изучение Java с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Java разработчик</span></a></div><div class='course'><a href='https://itproger.com/course/java-full'><div class='course-img'><img src='https://itproger.com/img/courses/1540641747.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Java до профи: основы, UI дизайн и Android разработка</span></a></div><div class='course'><a href='https://itproger.com/course/java-android'><div class='course-img'><img src='https://itproger.com/img/courses/1497013085.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Java Android</span></a></div><div class='course'><a href='https://itproger.com/course/kotlin'><div class='course-img'><img src='https://itproger.com/img/courses/1567066613.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение языка Kotlin</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_web() {
	$("#test").prev().text("Чем бы вы хотели заниматься?");
	$("#test").html("<div onclick='chooseProffesionalSkills_web_design()'><div><img src='/img/lang_test/frontend.svg' alt='Создание дизайна и разметки сайта'><p>Внешний вид сайта (front-end)</p></div></div><div onclick='chooseProffesionalSkills_web_logic()'><div><img src='/img/lang_test/backend.svg' alt='Работа с сервером (backend)'><p>Работа с сервером (backend)</p></div></div>");
}

function chooseProffesionalSkills_web_design() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/javascript.svg' alt='JavaScript'><h3>Язык JavaScript</h3><a href='/tag/javascript' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Внешний вид сайта, Front-end, не состоит из лишь одного языка программирования. Для создания внешней части сайта необходимо изучить как минимум: HTML, CSS, SASS, Gulp, Bootstrap и JavaScript.<br><br>Набор не маленький, но это базовый набор для хорошего верстальщика. JavaScript, в свою очередь, обладает уймой библиотек и фреймворков, которые расширяют его функционал. Начните с базового комплекта и плавно передвигайтесь к изучению React JS, Vue JS, Angular и Node JS. Все дополнительные библиотеки не являются обязательными, но обладая навыками работы с ними вы сможете найти более высокооплачиваемую работу.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/html'><div class='course-img'><img src='https://itproger.com/img/courses/1476977240.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение HTML с нуля</span></a></div><div class='course'><a href='https://itproger.com/course/css'><div class='course-img'><img src='https://itproger.com/img/courses/1476977488.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение CSS</span></a></div><div class='course'><a href='https://itproger.com/course/sass'><div class='course-img'><img src='https://itproger.com/img/courses/1549891240.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение препроцессора SASS / SCSS</span></a></div><div class='course'><a href='https://itproger.com/course/gulp'><div class='course-img'><img src='https://itproger.com/img/courses/1549960024.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение таск-менеджера Gulp 4</span></a></div><div class='course'><a href='https://itproger.com/course/javascript-full'><div class='course-img'><img src='https://itproger.com/img/courses/1532598979.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение JavaScript: от нуля и до создания сайта</span></a></div><div class='course'><a href='http://itproger.com/intensive/front-end'><div class='course-img'><img src='/img/intensivs/front-end.svg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Полный курс: Профессия Front-end разработчик</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_web_logic() {
	$("#test").prev().text("Для какого направления нужен вам язык?");
	$("#test").html("<div onclick='chooseProffesionalSkills_web_logic_small()'><div><img src='/img/lang_test/freelance.svg' alt='Небольшой сайт или фриланс'><p>Небольшой сайт или фриланс</p></div></div><div onclick='chooseProffesionalSkills_web_logic_startups()'><div><img src='/img/lang_test/startup.svg' alt='Стартапы и небольшие компании'><p>Стартапы и небольшие компании</p></div></div><div onclick='chooseProffesionalSkills_web_logic_traditional()'><div><img src='/img/lang_test/company.svg' alt='Большие компании'><p>Большие компании</p></div></div>");
}

function chooseProffesionalSkills_web_logic_small() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/php.svg' alt='PHP'><h3>Язык PHP</h3><a href='/tag/php' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>PHP – наиболее популярный язык для веб программирования. По <noindex><a href='https://w3techs.com/technologies/overview/programming_language' target='_blank' rel='nofollow'>статистике</a></noindex> его используют около 80% всех веб сайтов мира. Если вам необходимо создать сайт для себя или поработать на фрилансе, то язык идеально вам подойдет.<br><br>Язык обладает большим объемом встроенных функций, позволяет выполнять все стандартные задачи, имеет большое комьюнити и легок в изучение.<br><br>Помимо языка PHP вам также потребуется: HTML, CSS, работа с базами данных SQL и немного JavaScript.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/php-mysql'><div class='course-img'><img src='https://itproger.com/img/courses/1476980064.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение PHP и MySQL</span></a></div><div class='course'><a href='https://itproger.com/course/wordpress'><div class='course-img'><img src='https://itproger.com/img/courses/1522696846.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Сайт на WordPress</span></a></div><div class='course'><a href='https://itproger.com/intensive/back-end'><div class='course-img'><img src='https://itproger.com/img/intensivs/back-end.svg' alt='Изучение Back end с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Back-end разработчик</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_web_logic_startups() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/python.svg' alt='Python'><h3>Язык Python</h3><a href='/tag/python' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Создатели стартапов зачастую используют различные новомодные технологии, по типу: Django, Node JS, Go, Rust и многие другие языки и технологии, что еще не стали столь популярными, но уже набирают базу поклонников.<br><br>Здесь, наиболее удобный варианты – Python (и фреймворк Django) или же JavaScript (и технология Node JS). Выбирать стоит между Python и JavaScript, при чём выбрать стоит тот, что больше нравится в плане синтаксиса написания кода (лично мы за Python 🤤).</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/python'><div class='course-img'><img src='https://itproger.com/img/courses/1479108898.jpg' alt='Изучение Python с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Python с нуля</span></a></div><div class='course'><a href='https://itproger.com/intensive/python'><div class='course-img'><img src='https://itproger.com/img/intensivs/python.svg' alt='Изучение Python с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Python разработчик</span></a></div><div class='course'><a href='https://itproger.com/course/django'><div class='course-img'><img src='https://itproger.com/img/courses/django.svg' alt='Изучение библиотеки Django'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение библиотеки Django</span></a></div><div class='course'><a href='https://itproger.com/course/node-js'><div class='course-img'><img src='https://itproger.com/img/courses/1510913647.jpg' alt='Уроки Node JS и Express для начинающих'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Уроки Node JS и Express для начинающих</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_web_logic_traditional() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/csharp.svg' alt='Ruby'><h3>Язык C#</h3><a href='/tag/csharp' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Многие крупные компании любят использовать более традиционный и надежный подход для создания сайтов, поэтому используют язык Ruby, C# или же Java. Определитесь какой язык вам больше подходит по синтаксису и изучайте именно его.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/asp-net'><div class='course-img'><img src='https://itproger.com/img/courses/1551371255.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение ASP.NET Core MVC. Создание сайтов на C#</span></a></div><div class='course'><a href='https://itproger.com/course/ruby'><div class='course-img'><img src='https://itproger.com/img/courses/1532975967.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение языка Ruby для начинающих</span></a></div><div class='course'><a href='https://itproger.com/course/ruby-on-rails'><div class='course-img'><img src='https://itproger.com/img/courses/1534335030.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Создание блога на Ruby On Rails</span></a></div><div class='course'><a href='https://itproger.com/course/java'><div class='course-img'><img src='https://itproger.com/img/courses/1478531306.jpg' alt='Изучение Java с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Java с нуля</span></a></div><div class='course'><a href='https://itproger.com/intensive/java'><div class='course-img'><img src='https://itproger.com/img/intensivs/java.svg' alt='Изучение Java с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Java разработчик</span></a></div><div class='course'><a href='https://itproger.com/intensive/csharp'><div class='course-img'><img src='https://itproger.com/img/intensivs/csharp.svg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия C# разработчик</span></a></div></div>" + btn + "</div>");
}	

function chooseProffesionalSkills_soft() {
	$("#test").prev().text("Под какую платформу вы хотите разрабатывать?");
	$("#test").html("<div onclick='chooseProffesionalSkills_soft_windows()'><div><img src='/img/lang_test/windows.svg' alt='Windows'><p>Windows</p></div></div><div onclick='chooseProffesionalSkills_soft_mac()'><div><img src='/img/lang_test/macintosh.svg' alt='Mac'><p>Mac</p></div></div><div onclick='chooseProffesionalSkills_soft_all()'><div><img src='/img/lang_test/pc_console.svg' alt='Все платформы'><p>Все платформы</p></div></div>");
}

function chooseProffesionalSkills_soft_windows() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/csharp.svg' alt='swift'><h3>Язык C#</h3><a href='/tag/csharp' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Язык C# был разработан компанией Microsoft и он идеально подходит для создания программ под Windows. Компания Microsoft всячески продвигает язык, обновляет его и разрабатывает большиство своих приложений на нём. Изучение C# позволит вам  создавать программы под Windows и запускать их на любом компьютере с ОС Microsoft.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/csharp'><div class='course-img'><img src='https://itproger.com/img/courses/1477042680.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение языка C# для начинающих</span></a></div><div class='course'><a href='https://itproger.com/intensive/csharp'><div class='course-img'><img src='https://itproger.com/img/intensivs/csharp.svg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия C# разработчик</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_soft_mac() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/swift.svg' alt='swift'><h3>Язык Swift</h3><a href='/tag/ios' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Разработка приложений и игр для iOS и Macintosh производится на языке <b>Swift</b>. Язык продвигается компанией Apple, поэтому его популярность постоянно растет. Язык имеет простой синтаксис, удобную среду разработки и большой набор функций, что позволяет создавать проекты любой сложности.</p><h3>Подходящий курс</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/swift'><div class='course-img'><img src='https://itproger.com/img/courses/1523436361.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Уроки Swift для начинающих</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_soft_all() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/java.svg' alt='Java'><h3>Язык Java</h3><a href='/tag/java' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Java - удобный, быстрый и многофункционалный язык, который может выполняться вне зависимости от операционной системы: Windows, Mac или Linux.<br><br>Это свойство полюбили многие компании, которые используют данный язык для разработки своих приложений под ПК. Язык Java – один из лучших вариантов для создания кроссплатформенных приложений.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/java'><div class='course-img'><img src='https://itproger.com/img/courses/1478531306.jpg' alt='Изучение Java с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Java с нуля</span></a></div><div class='course'><a href='https://itproger.com/course/java-full'><div class='course-img'><img src='https://itproger.com/img/courses/1540641747.jpg'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Java до профи: основы, UI дизайн и Android разработка</span></a></div><div class='course'><a href='https://itproger.com/intensive/java'><div class='course-img'><img src='https://itproger.com/img/intensivs/java.svg' alt='Изучение Java с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Java разработчик</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_data() {
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");		
	$("#test").html("<div class='result'><img src='/img/lang_test/python.svg' alt='Python'><h3>Язык Python</h3><a href='/tag/python' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p>Python обладает большим набором библиотек, позволяющих обрабатывать большие потоки информации. Изучение Python для данной сферы считается наиболее хорошим вариантом, так как в Интернете вы найдете много обучающего материала, а сам язык не составит для вас больших проблем в плане изучения.<br><br>Если легкие пути вас не интересуют, то вам стоит погрузиться в язык программирования <a href='https://www.r-project.org/'>R</a>. Данный язык был специально разработан для обработки больших объемов данных.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/python'><div class='course-img'><img src='https://itproger.com/img/courses/1479108898.jpg' alt='Изучение Python с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Python с нуля</span></a></div><div class='course'><a href='https://itproger.com/intensive/python'><div class='course-img'><img src='https://itproger.com/img/intensivs/python.svg' alt='Изучение Python с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Python разработчик</span></a></div></div>" + btn + "</div>");
}

function chooseProffesionalSkills_ai() {
	$("#restart").show();
	$("#test").prev().text("Мы подобрали подходящий для вас язык программирования!");
	$("#test").html("<div class='result'><img src='/img/lang_test/python.svg' alt='Python'><h3>Язык Python</h3><a href='/tag/python' class='btn red tag-course'>Посмотреть все подходящие курсы <i class='fas fa-video'></i><div class='btn__blobs'><div></div><div></div><div></div></div></a><p><b>Python</b> – хороший язык для разработки искусственного интеллекта. Язык легкий, удобный и многофункциональный. Его с легкостью можно применять для создания прототипов ИИ. Разработка ИИ базируется на написании математических формул, просчете данных и построении математической модели для принятия решений. Изучив Python вы не научитесь создавать умные ИИ, так как вам потребуются еще хорошие знания в математике. Тем не менее, благодаря языку вы сможете описывать всю логику и функции ваших программ.</p><h3>Подходящие курсы</h3><div class='allResultCourses'><div class='course'><a href='https://itproger.com/course/python'><div class='course-img'><img src='https://itproger.com/img/courses/1479108898.jpg' alt='Изучение Python с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Изучение Python с нуля</span></a></div><div class='course'><a href='https://itproger.com/intensive/python'><div class='course-img'><img src='https://itproger.com/img/intensivs/python.svg' alt='Изучение Python с нуля'><div class='button-on-course'><i class='fas fa-play'></i></div></div><span class='title_course'>Профессия Python разработчик</span></a></div></div>" + btn + "</div>");
}